# This file is provided as supplemental material to the publication "Machine learning for small data sets: an exemplary study on the classification of highly complex surface micromorphologies" 
# by M. Henkel, M. Sprenger, and O. Lieleg submitted to Materials Today Advances on October 17th, 2025.

batch_size: 25
num_epochs: 5 #0

dropout_rate_CONV: 0 
dropout_rate_FC: 0 
image_size: 144
kernel_size: 3
learning_rate_classifier: 0.001
learning_rate_feature_extractor: 0.0001
patience: 8

include_NOD: true
num_classes: 4                            # Specify only the number of base classes [ABR; ADH; ERO; NOD] here. Dual classes combinations will be added automatically.

treshold_ABR: 0.5
treshold_ADH: 0.5
treshold_ERO: 0.5
treshold_NOD: 0.5

val_ratio: 0.15
train_ratio: 0.7
samples_per_class: 50

Freeze: false
unfrozen_layers: ["fc1", "fc2", "fc3"] 

data_augmentation: true
multiply_training_data: 10