# This file is provided as supplemental material to the publication "Machine learning for small data sets: an exemplary study on the classification of highly complex surface micromorphologies" 
# by M. Henkel, M. Sprenger, and O. Lieleg submitted to Materials Today Advances on October 17th, 2025.

batch_size: 50
learning_rate: 0.001
num_classes: 7
image_size: 144 
kernel_size: 3
dropout_rate_FC: 0.2        
dropout_rate_CONV: 0.25      



